config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  draw :api
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations',
     confirmations: 'users/confirmations'
   }
   root "commodities#index"

  resources :home
  resources :commodities
  resources :users
  resources :orders do
    member do
      get :pay_result
      put :pay
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to  :commodity
  belongs_to  :user

  enum status: {paying: 0, paid: 1, failed: 2, refund: 3, cancel: 4}
  before_save do
    self.discount ||= 0
    self.price = (1 - self.discount) * self.origin_price
    self.status ||= 0
  end

  def status_mapped
    I18n.t("enum.order.status.#{status}")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_commodity, only: [:new, :create]
  before_action :set_order, only: [:show, :pay, :pay_result]
  layout 'sessions', only:[ :pay_result]
  def index
  end

  def new

  end

  def create
    _total_price = params[:price].to_f * params[:count].to_f
    _no = "D#{Time.now.to_i}#{current_user.id}#{SecureRandom.random_number(0..999999).to_s.rjust(6, '0')}"
    @order = current_user.orders.build(origin_price: _total_price, commodity: @commodity, no: _no)
    if @order.save
      flash[:success] = "订单创建成功!"
      redirect_to order_path(@order)
    else
      render 'new'
    end
  end

  def show
    @commodity = @order.commodity
  end

  def pay
    @account = current_user.user_account
    Order.transaction do
      payment_code, message = PaymentCore.pay_money(amount: @order.price, user_acccount_id: @account.id)
      if PaymentCore.is_pay_success?(payment_code)
        flash[:success] = message
        @order.status = Order.statuses[:paid]
      else
        flash[:error] = message
        @order.status = Order.statuses[:failed]
      end
      @order.save
    end

    redirect_to pay_result_order_path(@order)
  end

  def pay_result
  end

  private
  def set_commodity
    @commodity = Commodity.find(params[:commodity_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<div class="container">
  <div class="container-header">
    <h1 class="blog-title">生成订单</h1>
    <p class="lead blog-description"></p>
  </div>
  <div class="row">
    <div class="container">
      <div id="tab" class="row">
        <div class="col-md-12 bg-f8f8f8">
          <div class="col-md-12">
            <hr>
            <div class="table-responsive">
              <%= form_for Order.new do %>
                <!--class= table-striped 无边框 table-bordered 有边框-->
                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>商品名</th>
                    <th>商品单价(<%= t("money") %>)</th>
                    <th>数量</th>
                    <th>商品总价(<%= t("money") %>)</th>
                    <th>操作</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td>
                      <%= hidden_field_tag :commodity_id, @commodity.id%>
                      <%= hidden_field_tag :price, @commodity.price.to_f%>
                    </td>
                    <td><%= @commodity.name %></td>
                    <td><%= @commodity.price %></td>
                    <td><%= text_field_tag :count, 1 %></td>
                    <td><%= @commodity.price  %></td>
                    <td>
                      <button class="btn btn-default">立即付款 »</button>
                    </td>
                  </tr>
                  </tbody>
                </table>
              <%end %>
            </div>
          </div>
          <div>
            <span>
              <%= @commodity.introduction%>
            </span>
          </div>
          <div>
            <span >
               <%= image_tag @commodity.first_image_url %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#count").on("input", function(){
    if($(this).val() == "")
      $(this).val(1)
    _count = parseFloat($(this).val())
    _price = parseFloat($(this).parent().prev().text())

    $(this).parent().next().text( _count * _price)
    })
</script>

app/views/orders/pay_result.html.erb
<div class="container">
  <%if flash.present? %>
    <div class="container-header">
      <h1 class="blog-title">订单<%= @order.no %></h1>
      <p class="lead blog-description"><%= flash[:success] || flash[:error]  %></p>
    </div>
    <div class="row">
      <div class="container">
        <div id="tab" class="row">
          <div class="col-md-12 bg-f8f8f8">
            <div class="col-md-12">
              <hr>
              <%= link_to "订单详情", order_path(@order) %>
            </div>
            <div class="col-md-12">
              <hr>
              您的账户余额(<%= t("money") %>): <%= current_user.user_account.amount.to_f %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%else %>
    <div class="row">
      <div class="container">
        <div id="tab" class="row">
          <div class="col-md-12 bg-f8f8f8">
            <div class="col-md-12">
              <hr>
              当前页面已经失效!<%= link_to "返回首页", "/" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="container-header">
    <h1 class="blog-title">订单详情(<%= @order.status_mapped %>)</h1>
    <p class="lead blog-description"></p>
  </div>
  <div class="row">
    <div class="container">
      <div id="tab" class="row">
        <div class="col-md-12 bg-f8f8f8">

          <!--<div class="col-md-12">-->
            <!--<hr>-->
            <!--您的账户余额(<%= t("money") %>): <f class='amount' ><%= current_user.user_account.amount.to_f %></f>-->
          <!--</div>-->
          <div class="col-md-12">
            <hr>
            收货地址: <%= current_user.default_address %>
          </div>

          <div class="col-md-12">
            <hr>
            商品总价格(<%= t("money") %>): <f class='amount' ><%= @order.price %></f>
          </div>

          <% if @order.status.in? %w(paying failed) %>
            <div class="col-md-12">
              <hr>
              <%= form_for @order, method: :put, url: pay_order_path(@order) do %>
              <%= button_tag '确认付款 »', class: "btn btn-primary" %>
              <%end %>
            </div>
          <% end %>
          <div class="col-md-12">
            <hr>
            付款方式[pay style]: 账户余额(<%= current_user.user_account.amount.to_f %>)  目前只支持账户余额
          </div>
        </div>
      </div>
    </div>
  </div>
</div>