config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  draw :api
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations',
     confirmations: 'users/confirmations'
   }
   root "commodities#index"

  resources :home
  resources :commodities
  resources :users
  resources :orders do
    member do
      get :pay_result
      put :pay
    end
  end
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  belongs_to :category, counter_cache: true
  has_many :attachments, as: :attachmentable

  def first_image_url
    if attachments.exists?
      attachments.first.file_url
    else
      "demo_product.jpg"
    end

  end
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  def index
    @commodities = Commodity.page(params[:page]).per(params[:per_page])
  end
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/views/commodities/index.html.erb
<div class="container">
  <div class="container-header">
    <h1 class="blog-title">欢迎来到OnlinePay</h1>
    <p class="lead blog-description">祝您购物愉快!</p>
  </div>
  <div class="row">
    <div class="container">
      <div id="tab" class="row">
        <% @commodities.each do |commodity|  %>
          <div class="col-md-4 h-280 bg-f8f8f8">
            <h4><a href="<%= new_order_path(commodity_id: commodity) %>"><%= commodity.name %>(<%= t("money") %><%=  commodity.price %>)</a></h4>
            <div class="h-180">
              <span class="f-left">
                <a href="<%= new_order_path(commodity_id: commodity) %>"><%= image_tag commodity.first_image_url, class: "w-120 h-120" %></a>
              </span>
              <span>
                <a href="<%= new_order_path(commodity_id: commodity)%>"><%= deal_string(commodity.introduction, 75)%></a>
              </span>
            </div>
            <p><a class="btn btn-default" href="<%= new_order_path(commodity_id: commodity) %>" role="button">立即购买 »</a></p>
          </div>
        <%end %>
        <%if @commodities.blank? %>
          <div class="col-md-12">
            <h3>暂无商品</h3>
          </div>
        <%end %>
      </div>
    </div>
  </div>
</div>